### PR TITLE
Update Catalan words

### PR DESCRIPTION
**Pull request by jmontane**
I've added variants for "one" (u / un), and "eight" (vuit / huit)

### CODE REVIEW

**Comment by JRMeyer** [comment]
@jmontane - what's the context for the variants? If you were reading out numbers over the phone, from your bank card, which would you use?

**Comment by jmontane** [comment]
well, I'll try to be clear enough.

About "u / un": "u" is the name for number 1 (one), but if you count something, then you say "un" (one). For example: "número u" (number one), but "un cotxe" (one car). There are contexts where you can use any form "u / un": counting  series (1,2,3...) "u/un, dos, tres,..." or spelling-out a phone number (93; 1,2,3...) "noranta-tres, u/un, dos, tres..."

About "vuit / huit": "huit" is form used by Valencian speakers, and it's full equivalent to general "vuit" form in all contexts. It's something similar to "color /colour" for American and British English.

**Comment by jmontane** [comment]
BTW,
I don't know If you want take gender in case. If gender is important:

Number 2 is spelled "dos" (male form) and "dues" (female form)
Number 1 is spelled "u / un" (male form) and "una" (female form)

**Comment by ftyers** [comment]
@JRMeyer 'huit' is just the Valencian form of the word. If I'm reading out digits I'll say 'huit', even if it's written 'vuit'. 'u' is the numeral, 'un' is the determiner (generally)

**Comment by JRMeyer** [comment]
@jmontane @ftyers - it sounds like we only want "u" for 1, but I'm confused about "huit" for 8... is it actually spelled that way in Valencia, or just pronounced that way?

It seems like for the current use-case (reading of isolated numerals, not determiners/adjectivals) we should keep as-is, and not merge. Can we get some clarification for this specific use-case?

**Comment by ftyers** [comment]
@JRMeyer You can spell it like that, but you don't have to. I say "huit" but usually I write "vuit". I would keep "vuit" and just let people pronounce it "huit" if that's in their dialect. I guess the closest thing in English would be words like "dreamed", which I would pronounce /drempt/ and not /drimd/

**Comment by JRMeyer** [comment]
I'm going to close this for now, because the variation seems relevant only outside the scope of the current project. 

nevertheless, thank you @jmontane for raising this point!

**Pull request closed without merging**
