### PR TITLE
Update with Danish numbers.

### PR DESCRIPTION
**Pull request by Isomorph70**
Added Danish numbers.

### CODE REVIEW

**Comment by JRMeyer** [comment]
tak!

**Comment by ole-tange** [comment]
Hey, Svend

You think too much in English :)

3 = tre (and not tree).

(Did you know that we are trying to get access to the Parliaments recordings + transcripts (in total ~5000 hours!)? All politicians we have spoken to are on board, but Ophavsretsloven §26 blocks us currently.)

**Comment by Isomorph70** [comment]
Hey Ole.

Thanks for catching the error. Have a tendency to be a little to fast at times.

I didn't know exactly what you are trying, but I did see a user tange, somewhere in the Riot group and was wondering, if it was you. 

Did you see that I also made a data extraction from the European Parliaments transcription?

**Comment by Isomorph70** [comment]
Here it is https://github.com/mozilla/voice-web/pull/2730 . But we need some Danish readers to verify the sentences for quality assurance.

**Comment by ole-tange** [comment]
I heard about it - I did not see it though.

**Pull request merged**
