### PR TITLE
update Esperanto

### PR DESCRIPTION
**Pull request by stefangrotz**
This is a small fix of the existing collection. The word nulo exists in Esperanto, but you count with the word "nul" nulo is zero as a substantive like "the zero".

I am not a native speaker, but I speak Esperanto for almost 15 years and I learned it from a native Esperanto speaker.

### CODE REVIEW

**Comment by JRMeyer** [comment]
Hi Stefan, I know finding native speakers for Esperanto is non-trivial, but could you try to run this by someone you know who is "native" or "native-like"?

Thanks for the PR!

**Comment by RobinvanderVliet** [comment]
This is a better source (compared to Wikipedia) for the names of the numbers: https://bertilow.com/pmeg/gramatiko/nombroj/vortetoj/formoj.html

Both "nul" and "nulo" are possible, but in this case I would prefer the form "nul".

I speak fluent Esperanto, I have done a CEFR exam on Esperanto at C1 level.

**Comment by LaPingvino** [comment]
I'm the President of TEJO, the World Esperanto Youth Organization, also speaking the language for a bit more than 15 years and I confirm what @RobinvanderVliet says. If you want to be very conservative, you could stick to the nulo form. It really depends on sticking to actual usage or being factually correct, and really both are used in practice.

**Comment by JRMeyer** [comment]
@lapingvino - the most illustrative use case is the following: you're reading your credit card number over the phone, number-by-number, to a machine. In this case (phone-based human-computer interaction) would you use `nul` or `nulo`?

I'm glad to see so many proficient speakers contributing on this! Thank you:)

**Comment by stefangrotz** [comment]
In this case I would go with nul. The online version of the PIV, the biggest monolingual dictionary of Esperanto, [(english wikipedia article)](https://en.wikipedia.org/wiki/Plena_Ilustrita_Vortaro_de_Esperanto)  also uses it this way: http://vortaro.net/#nul

> 2. La cifero 0: tri komo nul ok (3,08).

**Pull request merged**
