### PR TITLE
fix Japanese digits

### PR DESCRIPTION
**Pull request by marsf**

### CODE REVIEW

**Comment by marsf** [comment]
I added 2 pronounces to each item. They are formal and traditional in Japanese.

**Comment by JRMeyer** [comment]
Thanks, @marsf! Is the format [formal / informal]?

Is it more common to use one or the other on the phone (like if you're calling your bank and giving an account number?)

-josh

**Comment by marsf** [comment]
> Thanks, @marsf! Is the format [formal / informal]?

No, they are both commonly used in oral communication. I mean they are mixed in use.
For example, "12月2日" (December 2) is pronounced "じゅう に がつ (1 2 月) ふつ か (2 日)".
"2日" is also acceptable  as "に にち".

> Is it more common to use one or the other on the phone (like if you're calling your bank and giving an account number?)

It uses "formal" one for account number or phone number.

**Comment by JRMeyer** [comment]
What is the left / right order of formal / informal. For 0: れい / まる... which one is formal and which is informal?

**Comment by marsf** [comment]
They are [formal / traditional]. You can use all left side items.

**Comment by iveskins** [comment]
I might use まる  for 0 in an address and れい in a phone number. I'm not a native speaker, but the different pronunciations are really situational.

**Comment by JRMeyer** [comment]
@marsf any thoughts on @iveskins comment?

**Comment by marsf** [comment]
I totally agree with @iveskins.

Just I commented above, they are both used.
At the right side of "/" words, I call them "traditional", and they ARE NOT "Informal".

**Pull request merged**
