### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MohammedBelkacem**
Keep only informal forms for Kabyle

### CODE REVIEW

**Comment by JRMeyer** [comment]
Hi @mozillakab -- can you confirm that informal numbers are preferred for this use case: talking to an automatic system over the phone?

**Comment by JRMeyer** [comment]
@mozillakab -- ping

**Comment by MohammedBelkacem** [comment]
@JRMeyer  yes, informal numbers are mostly used and then preferred. Formal numbers are only used at school.

**Comment by JRMeyer** [comment]
thanks for confirming, I'll take the formal numbers out

**Comment by JRMeyer** [comment]
c72ebccccf7cbf13c77567691f1de3273b758032

**Pull request closed without merging**
