### PR TITLE
Update README.md- Arabic

### PR DESCRIPTION
**Pull request by Rubaaw**
Number 9 and 2 were written wrong

### CODE REVIEW

**Comment by JRMeyer** [comment]
Hi @Rubaaw,

Thanks for the PR! Are you a native speaker, and you're correcting based on your knowledge of Modern Standard Arabic (fusHa)? Other Arabic speakers have looked at this and not seen these issues, so I want to be sure.

If yes, then can you also change `NO` to `YES` in the last column?

Thank you!

**Comment by Rubaaw** [comment]
Hi @JRMeyer
Yes, I am a native Arabic speaker, also am a contributor at Mozilla L10n - Arabic team.

**Comment by JRMeyer** [comment]
Thanks again!

**Comment by Rubaaw** [comment]
My pleasure 🌹

**Pull request merged**
