### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by greenbrown**
Indonesian language verified.

### CODE REVIEW

**Comment by JRMeyer** [comment]
Thanks, @greenbrown !

**Comment by greenbrown** [comment]
May I know, how long it will take to be up in the Common Voice site?

**Comment by JRMeyer** [comment]
Unfortunately, I don't have a good answer for you:(

However, you can find the people with answers on Discourse:)

https://discourse.mozilla.org/t/help-create-common-voices-first-target-segment/59587

**Comment by greenbrown** [comment]
Ah, hehe okay, thank you @JRMeyer :)

**Pull request merged**
